//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreComputer.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class DatHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DatHang()
        {
            this.ChiTietDatHangs = new HashSet<ChiTietDatHang>();
        }
        [DisplayName("Mã hóa đơn")]
        public int maHD { get; set; }
        [DisplayName("Tên khách hàng")]
        [Required(ErrorMessage ="Vui lòng nhập tên khách hàng")]
        public string tenKhachHang { get; set; }
        [DisplayName("Số điện thoại")]
        [Required(ErrorMessage = "Vui lòng nhập số điện thoại khách hàng")]
        public string sdtKhachHang { get; set; }
        [DisplayName("Địa chỉ")]
        [Required(ErrorMessage = "Vui lòng nhập địa chỉ khách hàng")]
        public string diaChi { get; set; }
        [DisplayName("Ghi chú")]
        [Required(ErrorMessage = "Vui lòng nhập ghi chú khách hàng")]
        public string ghiChu { get; set; }
        [DisplayName("Số lượng")]
        public Nullable<int> soLuong { get; set; }
        [DisplayName("Tổng tiền")]
        public Nullable<double> tongTien { get; set; }
        [DisplayName("Phương thức thanh toán")]
        public string ptThanhToan { get; set; }
        [DisplayName("Tình trạng thanh toán")]
        public string tinhtrangThanhToan { get; set; }
        [DisplayName("Tình trạng đơn hàng")]
        public string tinhtrangDonHang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDatHang> ChiTietDatHangs { get; set; }
    }
}
