//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreComputer.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class HangHoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HangHoa()
        {
            this.ChiTietDatHangs = new HashSet<ChiTietDatHang>();
        }
        [DisplayName("Mã hàng")]

        public int maHang { get; set; }
        [DisplayName("Mã loại")]
        public int maLoai { get; set; }
        [DisplayName("Mã nhà cung cấp")]
        public int maNCC { get; set; }
        [DisplayName("Tên hàng")]
        [Required(ErrorMessage ="Vui lòng nhập tên hàng hóa")]
        public string tenHang { get; set; }
        [DisplayName("Ngày nhập")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{dd/mm/yyyy}")]
        public System.DateTime ngayNhap { get; set; }
        [DisplayFormat(DataFormatString = "{dd/mm/yyyy}")]
        [DisplayName("Giá mới")]
        [Required(ErrorMessage = "Vui lòng nhập giá mới hàng hóa hàng hóa")]
        public double giaMoi { get; set; }
        [DisplayName("Giá cũ")]
        public double giaCu { get; set; }
        [DisplayName("Số lượng")]
        [Required(ErrorMessage = "Vui lòng nhập số lượng hàng hóa")]
        public int soLuong { get; set; }
        [DisplayName("Hình ảnh")]
        [Required(ErrorMessage = "Vui lòng nhập hình ảnh hàng hóa")]
        public string hinhAnh { get; set; }
        [DisplayName("Mô tả")]
        [Required(ErrorMessage = "Vui lòng nhập mô tả hàng hóa")]
        public string moTa { get; set; }
        [DisplayName("Mô tả chi tiết")]
        [Required(ErrorMessage = "Vui lòng nhập mô tả chi tiết hàng hóa")]
        public string maTaChiTiet { get; set; }
        [DisplayName("Giảm giá")]
        public string giamGia { get; set; }
        [DisplayName("Trạng thái sản phẩm")]
        [Required(ErrorMessage = "Vui lòng nhập trạng thái hàng hóa")]
        public string trangThaiSP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDatHang> ChiTietDatHangs { get; set; }
        public virtual LoaiHang LoaiHang { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
    }
}
